version: '3.6'
services:
  db:
    image: postgres:9.6-alpine
    ports: [5432]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./bd.sql:/docker-entrypoint-initdb.d/bd.sql
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: banco
      DB_HOST: db
      DB_PORT: 5432
    links:
      - db
    volumes:
      - ./:/src
volumes:
  db:
    driver: local
